# Generated by Django 4.0.4 on 2022-06-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.IntegerField(primary_key=True, serialize=False)),
                ('client', models.CharField(max_length=200)),
                ('deck', models.CharField(max_length=200)),
                ('english', models.CharField(max_length=200)),
                ('polish', models.CharField(max_length=200)),
                ('publication_date', models.IntegerField()),
                ('due_date', models.IntegerField()),
                ('interval', models.IntegerField()),
                ('number_of_reviews', models.IntegerField()),
                ('answers', models.CharField(max_length=200)),
                ('card_opening_times', models.CharField(max_length=200)),
                ('card_closing_times', models.CharField(max_length=200)),
                ('durations', models.CharField(max_length=200)),
                ('card_revision_days', models.CharField(max_length=200)),
                ('line', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('test_user', models.CharField(max_length=200)),
                ('name', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('phone_number', models.IntegerField()),
                ('contact_email_address', models.CharField(default='', max_length=200)),
                ('school', models.CharField(default='Nieszkolni', max_length=200)),
                ('internal_email_address', models.CharField(default='', max_length=200)),
                ('meeting_duration', models.IntegerField(default=55)),
                ('price', models.IntegerField()),
                ('acquisition_channel', models.CharField(default='', max_length=200)),
                ('recommenders', models.CharField(default='', max_length=200)),
                ('reasons_for_resignation', models.CharField(default='', max_length=200)),
                ('status', models.CharField(default='', max_length=200)),
                ('coach', models.CharField(default='', max_length=200)),
                ('level', models.CharField(default='', max_length=200)),
                ('daily_limit_of_new_cards', models.IntegerField(default=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentClient',
            fields=[
                ('coach', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('item', models.IntegerField(primary_key=True, serialize=False)),
                ('deadline_text', models.CharField(default='', max_length=200)),
                ('deadline_number', models.IntegerField()),
                ('name', models.CharField(default='', max_length=200)),
                ('component_id', models.CharField(default='', max_length=200)),
                ('component_type', models.CharField(default='', max_length=200)),
                ('assignment_type', models.CharField(default='', max_length=200)),
                ('title', models.CharField(default='', max_length=200)),
                ('content', models.TextField(default='')),
                ('matrix', models.CharField(default='', max_length=200)),
                ('resources', models.CharField(default='', max_length=200)),
                ('status', models.CharField(default='uncompleted', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pronunciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_stamp', models.IntegerField()),
                ('publication_date', models.IntegerField()),
                ('coach', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('entry', models.CharField(default='', max_length=200)),
                ('due_date', models.IntegerField()),
                ('number_of_reviews', models.IntegerField()),
                ('answers', models.TextField(default='')),
                ('revision_days', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('stamp', models.IntegerField()),
                ('item', models.IntegerField()),
                ('name', models.CharField(default='', max_length=200)),
                ('assignment_type', models.CharField(default='', max_length=200)),
                ('title', models.CharField(default='', max_length=200)),
                ('content', models.CharField(default='', max_length=200)),
                ('wordcount', models.IntegerField()),
            ],
        ),
    ]
