# Generated by Django 4.0.4 on 2022-11-09 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spin',
            old_name='view_number',
            new_name='scene',
        ),
    ]
