# Generated by Django 4.0.4 on 2022-06-04 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pronunciation',
            unique_together={('name', 'entry')},
        ),
    ]
