# Generated by Django 4.0.4 on 2022-06-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0002_alter_pronunciation_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('english', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('polish', models.CharField(default='', max_length=200)),
                ('user', models.CharField(default='', max_length=200)),
                ('publication_date', models.IntegerField()),
            ],
        ),
    ]
