# Generated by Django 4.0.4 on 2022-11-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0002_client_maximal_interval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='daily_limit_of_new_cards',
            new_name='daily_limit_of_new_cards_vocabulary',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='maximal_interval',
            new_name='maximal_interval_vocabulary',
        ),
    ]
