# Generated by Django 4.0.4 on 2022-11-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0002_rename_view_number_spin_scene'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
                ('courses', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
