# Generated by Django 4.0.4 on 2022-11-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0003_rename_daily_limit_of_new_cards_client_daily_limit_of_new_cards_vocabulary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='daily_limit_of_new_cards_sentences',
            field=models.IntegerField(default=25, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='maximal_interval_sentences',
            field=models.IntegerField(default=90, null=True),
        ),
    ]
