# Generated by Django 4.0.4 on 2022-06-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0003_dictionary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wordbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('english', models.CharField(default='', max_length=200)),
                ('polish', models.CharField(default='', max_length=200)),
                ('publication_date', models.IntegerField()),
                ('publicating_user', models.CharField(default='', max_length=200)),
                ('translation_date', models.IntegerField()),
                ('translating_user', models.CharField(default='', max_length=200)),
                ('revision_date', models.IntegerField()),
                ('reviewing_user', models.CharField(default='', max_length=200)),
                ('status', models.CharField(default='', max_length=200)),
            ],
            options={
                'unique_together': {('name', 'english')},
            },
        ),
    ]
