# Generated by Django 4.0.4 on 2022-11-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0003_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='degree',
            field=models.CharField(default='', max_length=200),
        ),
    ]
