# Generated by Django 4.0.4 on 2022-06-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0004_wordbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='answers',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_closing_times',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_opening_times',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_revision_days',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='durations',
            field=models.TextField(default=''),
        ),
    ]
