# Generated by Django 4.0.4 on 2022-11-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0004_client_daily_limit_of_new_cards_sentences_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='daily_limit_of_new_cards_sentences',
            new_name='daily_limit_of_new_sentences',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='daily_limit_of_new_cards_vocabulary',
            new_name='daily_limit_of_new_vocabulary',
        ),
    ]
