# Generated by Django 4.0.4 on 2022-11-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0004_program_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
