# Generated by Django 4.0.4 on 2022-11-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0005_program_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchword', models.IntegerField(default=0)),
                ('cue', models.CharField(default='', max_length=200)),
                ('response', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
