# Generated by Django 4.0.4 on 2022-06-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0005_alter_card_answers_alter_card_card_closing_times_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='coach',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
