# Generated by Django 4.0.4 on 2022-06-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0006_card_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentencebook',
            fields=[
                ('english', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('polish', models.CharField(default='', max_length=200)),
                ('user', models.CharField(default='', max_length=200)),
                ('publication_date', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='wordbook',
            name='deck',
            field=models.CharField(default='', max_length=200),
        ),
    ]
