# Generated by Django 4.0.4 on 2022-06-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0007_sentencebook_wordbook_deck'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wordbook',
            new_name='Book',
        ),
        migrations.DeleteModel(
            name='Sentencebook',
        ),
        migrations.AddField(
            model_name='dictionary',
            name='entry_type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
