# Generated by Django 4.0.4 on 2022-06-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0008_rename_wordbook_book_delete_sentencebook_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionary',
            old_name='entry_type',
            new_name='deck',
        ),
    ]
