# Generated by Django 4.0.4 on 2022-06-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0010_catalogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='publicating_user',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='publication_date',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
