# Generated by Django 4.0.4 on 2022-06-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0011_catalogue_publicating_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(default='', max_length=200)),
                ('parent', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
