# Generated by Django 4.0.4 on 2022-06-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0012_prompt'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prompt',
            unique_together={('prompt', 'parent')},
        ),
    ]
