# Generated by Django 4.0.4 on 2022-11-22 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0012_ticket_assigned_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='importance',
            new_name='sentiment',
        ),
    ]
