# Generated by Django 4.0.4 on 2022-06-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0013_alter_prompt_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_stamp', models.IntegerField()),
                ('publication_date', models.IntegerField()),
                ('coach', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('prompt', models.CharField(default='', max_length=200)),
                ('left_option', models.CharField(default='', max_length=200)),
                ('right_option', models.CharField(default='', max_length=200)),
                ('due_date', models.IntegerField()),
                ('number_of_reviews', models.IntegerField()),
                ('answers', models.TextField(default='')),
                ('revision_days', models.TextField(default='')),
            ],
        ),
    ]
