# Generated by Django 4.0.4 on 2022-11-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0013_rename_importance_ticket_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='response',
            field=models.TextField(default=''),
        ),
    ]
