# Generated by Django 4.0.4 on 2022-11-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0014_ticket_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='closing_stamp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='response_time',
            field=models.IntegerField(default=0),
        ),
    ]
