# Generated by Django 4.0.4 on 2022-06-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0014_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='pattern',
            field=models.CharField(default='', max_length=200),
        ),
    ]
