# Generated by Django 4.0.4 on 2022-06-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0015_prompt_pattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='prompt',
        ),
        migrations.AddField(
            model_name='memory',
            name='prompt',
            field=models.ManyToManyField(to='nieszkolni_app.prompt'),
        ),
    ]
