# Generated by Django 4.0.4 on 2022-11-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0015_ticket_closing_stamp_ticket_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='item',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='composer',
            name='submission_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='composer',
            name='submission_stamp',
            field=models.IntegerField(default=0),
        ),
    ]
