# Generated by Django 4.0.4 on 2022-06-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0016_remove_memory_prompt_memory_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='prompt',
        ),
        migrations.AddField(
            model_name='memory',
            name='prompt',
            field=models.CharField(default='', max_length=200),
        ),
    ]
