# Generated by Django 4.0.4 on 2022-06-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0017_remove_memory_prompt_memory_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.IntegerField()),
                ('date', models.IntegerField()),
                ('name', models.CharField(default='', max_length=200)),
                ('command', models.CharField(default='', max_length=200)),
                ('value', models.CharField(default='', max_length=200)),
                ('user', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
