# Generated by Django 4.0.4 on 2022-11-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0018_audit_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit',
            old_name='tag',
            new_name='tags',
        ),
    ]
