# Generated by Django 4.0.4 on 2022-06-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0018_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='completion_date',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculum',
            name='completion_stamp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
