# Generated by Django 4.0.4 on 2022-06-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0019_curriculum_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='completion_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='completion_stamp',
            field=models.IntegerField(default=0),
        ),
    ]
