# Generated by Django 4.0.4 on 2022-12-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0020_rename_value_audit_category_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=200)),
                ('content', models.FileField(upload_to='')),
            ],
        ),
    ]
