# Generated by Django 4.0.4 on 2022-12-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0021_document'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Paper',
        ),
    ]
