# Generated by Django 4.0.4 on 2022-06-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0021_curriculum_submitting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='status',
            field=models.CharField(default='active', max_length=200),
        ),
    ]
