# Generated by Django 4.0.4 on 2022-12-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0022_rename_document_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
    ]
