# Generated by Django 4.0.4 on 2022-06-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0022_stream_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='date',
            new_name='date_number',
        ),
    ]
