# Generated by Django 4.0.4 on 2022-12-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0023_rating_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
