# Generated by Django 4.0.4 on 2022-06-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0023_rename_date_stream_date_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='date',
            field=models.CharField(default='', max_length=200),
        ),
    ]
