# Generated by Django 4.0.4 on 2022-12-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0024_alter_rating_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('duration', models.IntegerField(default=0)),
                ('title_type', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
