# Generated by Django 4.0.4 on 2022-06-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0025_alter_submission_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='submission',
            name='date_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
