# Generated by Django 4.0.4 on 2022-12-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0025_theater'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='set_type',
            field=models.CharField(default='sentences', max_length=200),
        ),
    ]
