# Generated by Django 4.0.4 on 2022-06-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0026_submission_date_submission_date_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='reviewed_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(default='submitted', max_length=200),
        ),
    ]
