# Generated by Django 4.0.4 on 2022-12-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0026_set_set_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix', models.CharField(default='', max_length=200)),
                ('step_type', models.CharField(default='', max_length=200)),
                ('step_number', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=200)),
                ('text', models.TextField(default='')),
                ('image', models.CharField(default='', max_length=200)),
                ('module', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
