# Generated by Django 4.0.4 on 2022-12-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0027_challengematrix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.IntegerField(default=0)),
                ('matrix', models.CharField(default='', max_length=200)),
                ('process_number', models.IntegerField(default=0)),
                ('process_status', models.CharField(default='', max_length=200)),
                ('process_completion_stamp', models.IntegerField(default=0)),
                ('step_type', models.CharField(default='', max_length=200)),
                ('step_number', models.IntegerField(default=0)),
                ('step_status', models.CharField(default='', max_length=200)),
                ('step_completion_stamp', models.IntegerField(default=0)),
                ('client', models.CharField(default='', max_length=200)),
                ('title', models.CharField(default='', max_length=200)),
                ('text', models.TextField(default='')),
                ('image', models.CharField(default='', max_length=200)),
                ('module', models.CharField(default='', max_length=200)),
                ('item', models.IntegerField(default=0)),
            ],
        ),
    ]
