# Generated by Django 4.0.4 on 2022-06-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0027_submission_reviewed_content_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='reviewing_user',
            field=models.CharField(default='', max_length=200),
        ),
    ]
