# Generated by Django 4.0.4 on 2022-12-28 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0028_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='step_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='nieszkolni_app.challengematrix'),
            preserve_default=False,
        ),
    ]
