# Generated by Django 4.0.4 on 2022-06-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0028_submission_reviewing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='analysis',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='conditions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='flagged_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='submission',
            name='major_errors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='minor_errors',
            field=models.IntegerField(default=0),
        ),
    ]
