# Generated by Django 4.0.4 on 2022-06-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0029_submission_analysis_submission_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='conditions',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='resources',
            field=models.TextField(default=''),
        ),
    ]
