# Generated by Django 4.0.4 on 2023-01-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0030_alter_challenge_step_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('content', models.TextField(default='')),
                ('question_ids', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField(default='')),
                ('option_value', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='')),
                ('question_type', models.CharField(default='', max_length=200)),
                ('option_ids', models.CharField(default='', max_length=200)),
                ('action', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.IntegerField(default=0)),
                ('client', models.CharField(default='', max_length=200)),
                ('response', models.TextField(default='')),
                ('survey_id', models.IntegerField(default=0)),
                ('question_id', models.IntegerField(default=0)),
                ('response_id', models.IntegerField(default=0)),
                ('item', models.IntegerField(default=0)),
            ],
        ),
    ]
