# Generated by Django 4.0.4 on 2022-06-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0030_curriculum_conditions_alter_curriculum_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceStock',
            fields=[
                ('sentence_id', models.IntegerField(primary_key=True, serialize=False)),
                ('polish', models.TextField(default='')),
                ('english', models.TextField(default='')),
                ('glossary', models.TextField(default='')),
            ],
        ),
    ]
