# Generated by Django 4.0.4 on 2023-01-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0031_survey_surveyoption_surveyquestion_surveyresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='activity_points',
            field=models.IntegerField(default=1),
        ),
    ]
