# Generated by Django 4.0.4 on 2022-06-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0031_sentencestock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('list_number', models.IntegerField()),
                ('sentence_number', models.IntegerField(primary_key=True, serialize=False)),
                ('sentence_id', models.IntegerField()),
                ('name', models.CharField(default='', max_length=200)),
                ('polish', models.TextField(default='')),
                ('english', models.TextField(default='')),
                ('glossary', models.TextField(default='')),
                ('submission_stamp', models.IntegerField()),
                ('submission_date', models.IntegerField()),
                ('status', models.CharField(default='', max_length=200)),
                ('translation', models.TextField(default='')),
                ('result', models.CharField(default='', max_length=200)),
                ('reviewing_user', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(default='', max_length=200)),
                ('sentence_id', models.IntegerField()),
            ],
        ),
    ]
