# Generated by Django 4.0.4 on 2023-01-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0032_challenge_activity_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='program',
            field=models.CharField(default='Custom Program', max_length=200),
        ),
    ]
