# Generated by Django 4.0.4 on 2022-06-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0032_composer_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='reference',
            field=models.IntegerField(default=0),
        ),
    ]
