# Generated by Django 4.0.4 on 2023-01-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0033_roadmap_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='client',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='deck',
            field=models.CharField(default='vocabulary', max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='due_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='english',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='line',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='number_of_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='polish',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='publication_date',
            field=models.IntegerField(default=0),
        ),
    ]
