# Generated by Django 4.0.4 on 2022-06-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0033_curriculum_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('position_number', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(default='')),
                ('wordcount', models.IntegerField()),
                ('link', models.TextField(default='')),
            ],
        ),
    ]
