# Generated by Django 4.0.4 on 2022-06-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0034_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('links', models.TextField(default='')),
                ('status', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
