# Generated by Django 4.0.4 on 2023-01-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0034_alter_card_client_alter_card_deck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='initiation_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='revision_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='translation_date',
            field=models.IntegerField(default=0),
        ),
    ]
