# Generated by Django 4.0.4 on 2023-01-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0035_card_initiation_date_alter_book_publication_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='catalogue_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='entry_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='publication_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='composer',
            name='list_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='composer',
            name='sentence_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='memory',
            name='due_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='memory',
            name='number_of_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='memory',
            name='publication_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='memory',
            name='publication_stamp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pronunciation',
            name='due_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pronunciation',
            name='number_of_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pronunciation',
            name='publication_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pronunciation',
            name='publication_stamp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='repertoire',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='repertoireline',
            name='date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='repertoireline',
            name='stamp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stream',
            name='date_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stream',
            name='stamp',
            field=models.IntegerField(default=0),
        ),
    ]
