# Generated by Django 4.0.4 on 2022-06-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0037_alter_libraryline_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repertoire',
            fields=[
                ('title', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('titile_type', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RepertoireLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('title', models.CharField(default='', max_length=200)),
                ('number_of_episodes', models.IntegerField()),
                ('status', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
