# Generated by Django 4.0.4 on 2023-01-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0037_book_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='test',
            field=models.CharField(default='', max_length=200),
        ),
    ]
