# Generated by Django 4.0.4 on 2023-01-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0038_grade_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Binder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binder', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(default='active', max_length=200),
        ),
    ]
