# Generated by Django 4.0.4 on 2022-06-21 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0038_repertoire_repertoireline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repertoire',
            old_name='titile_type',
            new_name='title_type',
        ),
    ]
