# Generated by Django 4.0.4 on 2023-01-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0039_binder_alter_client_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer',
            name='efficiency',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='composer',
            name='method',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='composer',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='composer',
            name='shape',
            field=models.CharField(default='', max_length=200),
        ),
    ]
