# Generated by Django 4.0.4 on 2022-06-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0039_rename_titile_type_repertoire_title_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='repertoireline',
            name='date',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repertoireline',
            name='stamp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
