# Generated by Django 4.0.4 on 2023-01-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0040_composer_efficiency_composer_method_composer_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer',
            name='reviewing_stamp',
            field=models.IntegerField(default=0),
        ),
    ]
