# Generated by Django 4.0.4 on 2022-07-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0040_repertoireline_date_repertoireline_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='revision_date',
            field=models.IntegerField(default=8224),
            preserve_default=False,
        ),
    ]
