# Generated by Django 4.0.4 on 2023-01-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0041_composer_reviewing_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composer',
            name='efficiency',
            field=models.CharField(default='', max_length=200),
        ),
    ]
