# Generated by Django 4.0.4 on 2023-01-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0042_alter_composer_efficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='binder',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
