# Generated by Django 4.0.4 on 2022-09-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0042_rename_user_stream_stream_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.IntegerField(default='000000000'),
        ),
        migrations.AlterField(
            model_name='client',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='school',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='test_user',
            field=models.CharField(default='No', max_length=200),
        ),
    ]
