# Generated by Django 4.0.4 on 2023-01-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0043_binder_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
