# Generated by Django 4.0.4 on 2022-09-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0044_alter_client_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('avatar', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='test_user',
        ),
        migrations.AddField(
            model_name='client',
            name='user_type',
            field=models.CharField(default='client', max_length=200),
        ),
    ]
