# Generated by Django 4.0.4 on 2022-09-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0045_profile_remove_client_test_user_client_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('roadmap_id_number', models.IntegerField(primary_key=True, serialize=False)),
                ('roadmap_matrix', models.CharField(default='', max_length=200)),
                ('semester', models.IntegerField(default=0)),
                ('course', models.CharField(default='', max_length=200)),
                ('course_type', models.CharField(default='', max_length=200)),
                ('course_description', models.TextField(default='')),
                ('registration_description', models.TextField(default='')),
                ('assessment_description', models.TextField(default='')),
                ('assessment_method', models.CharField(default='', max_length=200)),
                ('link', models.TextField(default='')),
                ('reference_system', models.CharField(default='', max_length=200)),
                ('threshold', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=200)),
                ('deadline_number', models.IntegerField(default=0)),
                ('planning_user', models.CharField(default='', max_length=200)),
                ('score_1_attempt', models.IntegerField(default=0)),
                ('grade_1_attempt', models.CharField(default='', max_length=200)),
                ('score_1_attempt_date_number', models.IntegerField(default=0)),
                ('examiner_1_attempt', models.CharField(default='', max_length=200)),
                ('score_2_attempt', models.IntegerField(default=0)),
                ('grade_2_attempt', models.CharField(default='', max_length=200)),
                ('score_2_attempt_date_number', models.IntegerField(default=0)),
                ('examiner_2_attempt', models.CharField(default='', max_length=200)),
                ('score_3_attempt', models.IntegerField(default=0)),
                ('grade_3_attempt', models.CharField(default='', max_length=200)),
                ('score_3_attempt_date_number', models.IntegerField(default=0)),
                ('examiner_3_attempt', models.CharField(default='', max_length=200)),
                ('status', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
