# Generated by Django 4.0.4 on 2022-09-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0046_roadmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(default='', max_length=200)),
                ('course_type', models.CharField(default='', max_length=200)),
                ('course_description', models.TextField(default='')),
                ('registration_description', models.TextField(default='')),
                ('assessment_description', models.TextField(default='')),
                ('assessment_method', models.CharField(default='', max_length=200)),
                ('link', models.TextField(default='')),
                ('reference_system', models.CharField(default='', max_length=200)),
                ('threshold', models.IntegerField(default=0)),
            ],
        ),
    ]
