# Generated by Django 4.0.4 on 2023-02-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0046_alter_client_wage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_stamp', models.IntegerField(default=0)),
                ('modification_stamp', models.IntegerField(default=0)),
                ('product_id', models.IntegerField(default=0)),
                ('seller', models.CharField(default='', max_length=200)),
                ('client', models.CharField(default='', max_length=200)),
                ('status', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_stamp', models.IntegerField(default=0)),
                ('modification_stamp', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
                ('category', models.CharField(default='', max_length=200)),
                ('points', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('allocation_per_client', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], default='', max_length=200)),
            ],
        ),
    ]
