# Generated by Django 4.0.4 on 2022-09-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0047_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
