# Generated by Django 4.0.4 on 2022-09-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0048_remove_course_id_alter_course_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='roadmap_id_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
