# Generated by Django 4.0.4 on 2023-02-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0049_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_program',
            field=models.CharField(default='', max_length=200),
        ),
    ]
