# Generated by Django 4.0.4 on 2022-10-01 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0049_alter_roadmap_roadmap_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmap',
            name='assessment_description',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='assessment_method',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='course_description',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='course_type',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='link',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='reference_system',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='registration_description',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='threshold',
        ),
    ]
