# Generated by Django 4.0.4 on 2022-10-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0050_remove_roadmap_assessment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_degree',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='early_admission',
            field=models.IntegerField(default=1),
        ),
    ]
