# Generated by Django 4.0.4 on 2023-02-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0050_profile_current_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_stamp', models.IntegerField(default=0)),
                ('modification_stamp', models.IntegerField(default=0)),
                ('start', models.IntegerField(default=0)),
                ('end', models.IntegerField(default=0)),
                ('procedure', models.CharField(default='', max_length=200)),
                ('method', models.CharField(default='', max_length=200)),
                ('threshold', models.IntegerField(default=0)),
                ('reward', models.IntegerField(default=0)),
                ('participants', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
