# Generated by Django 4.0.4 on 2023-02-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0051_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='participants',
            field=models.TextField(default=''),
        ),
    ]
