# Generated by Django 4.0.4 on 2023-02-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0052_alter_contest_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
    ]
