# Generated by Django 4.0.4 on 2022-10-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0052_profile_associate_specialization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='associate_specialization',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bachelor_specialization',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='doctorate_specialization',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='master_specialization',
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
    ]
