# Generated by Django 4.0.4 on 2023-02-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0053_contest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
