# Generated by Django 4.0.4 on 2022-10-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0054_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='id',
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
    ]
