# Generated by Django 4.0.4 on 2023-02-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0054_notification_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_stamp', models.IntegerField(default=0)),
                ('modification_stamp', models.IntegerField(default=0)),
                ('client', models.CharField(default='', max_length=200)),
                ('listing', models.CharField(default='', max_length=200)),
                ('status', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
