# Generated by Django 4.0.4 on 2022-10-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0055_remove_material_id_alter_material_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(default='', max_length=200)),
                ('recipient', models.CharField(default='', max_length=200)),
                ('subject', models.CharField(default='', max_length=200)),
                ('content', models.TextField(default='')),
                ('notification_type', models.CharField(default='', max_length=200)),
                ('status', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
