# Generated by Django 4.0.4 on 2023-02-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0055_taker'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='color',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='notification',
            name='limit',
            field=models.IntegerField(default=0),
        ),
    ]
