# Generated by Django 4.0.4 on 2023-02-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0056_notification_color_notification_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='limit',
        ),
        migrations.AddField(
            model_name='notification',
            name='condition',
            field=models.IntegerField(default=0),
        ),
    ]
