# Generated by Django 4.0.4 on 2023-02-09 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0057_remove_notification_limit_notification_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='condition',
            new_name='threshold',
        ),
    ]
