# Generated by Django 4.0.4 on 2022-10-24 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0057_notification_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmap',
            name='examiner_1_attempt',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='examiner_2_attempt',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='examiner_3_attempt',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='grade_1_attempt',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='grade_2_attempt',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='grade_3_attempt',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='score_1_attempt',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='score_1_attempt_date_number',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='score_2_attempt',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='score_2_attempt_date_number',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='score_3_attempt',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='score_3_attempt_date_number',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='status',
        ),
    ]
