# Generated by Django 4.0.4 on 2023-02-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0058_rename_condition_notification_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronunciation',
            name='status',
            field=models.CharField(default='active', max_length=200),
        ),
    ]
