# Generated by Django 4.0.4 on 2022-10-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0059_roadmap_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.IntegerField(default=0)),
                ('date_number', models.IntegerField(default=0)),
                ('student', models.CharField(default='', max_length=200)),
                ('course', models.CharField(default='', max_length=200)),
                ('result', models.CharField(default='', max_length=200)),
                ('grade', models.CharField(default='', max_length=200)),
                ('grade_type', models.CharField(default='', max_length=200)),
                ('examiner', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
