# Generated by Django 4.0.4 on 2022-10-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0061_remove_grade_grade_alter_grade_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.IntegerField(default=0)),
                ('date_number', models.IntegerField(default=0)),
                ('command', models.CharField(default='', max_length=200)),
                ('value', models.CharField(default='', max_length=200)),
                ('author', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
