# Generated by Django 4.0.4 on 2022-10-27 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0064_matrix_remove_module_limit_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='assignment_type',
        ),
    ]
