# Generated by Django 4.0.4 on 2022-10-27 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0065_remove_module_assignment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrix',
            name='assignment_type',
        ),
        migrations.RemoveField(
            model_name='matrix',
            name='component_type',
        ),
        migrations.RemoveField(
            model_name='matrix',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='matrix',
            name='content',
        ),
        migrations.RemoveField(
            model_name='matrix',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='matrix',
            name='title',
        ),
    ]
