# Generated by Django 4.0.4 on 2022-10-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0066_remove_matrix_assignment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='early_admission',
            field=models.CharField(default='no', max_length=200),
        ),
    ]
