# Generated by Django 4.0.4 on 2022-10-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0067_alter_profile_early_admission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionary',
            old_name='user',
            new_name='publicating_user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='early_admission',
            field=models.IntegerField(default=1),
        ),
    ]
