# Generated by Django 4.0.4 on 2022-10-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0068_rename_user_dictionary_publicating_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='reference',
            field=models.IntegerField(default=0),
        ),
    ]
