# Generated by Django 4.0.4 on 2022-10-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0069_module_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='component_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='item',
            field=models.IntegerField(default=0),
        ),
    ]
