# Generated by Django 4.0.4 on 2022-11-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0069_module_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='component_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='item',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='revision_date',
            field=models.IntegerField(default=0),
        ),
    ]
