# Generated by Django 4.0.4 on 2022-11-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0070_course_component_id_roadmap_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='status_type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
