# Generated by Django 4.0.4 on 2022-11-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0071_roadmap_status_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=200)),
                ('question', models.CharField(default='', max_length=200)),
                ('answer_a', models.CharField(default='', max_length=200)),
                ('answer_b', models.CharField(default='', max_length=200)),
                ('answer_c', models.CharField(default='', max_length=200)),
                ('answer_d', models.CharField(default='', max_length=200)),
                ('correct_answer', models.CharField(default='', max_length=200)),
                ('question_type', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
