# Generated by Django 4.0.4 on 2022-11-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0072_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.IntegerField(default=0)),
                ('question_id', models.IntegerField(default=0)),
                ('client', models.CharField(default='', max_length=200)),
                ('answer', models.CharField(default='', max_length=200)),
                ('result', models.CharField(default='', max_length=200)),
                ('date_number', models.IntegerField(default=0)),
            ],
        ),
    ]
