# Generated by Django 4.0.4 on 2022-11-01 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0073_quiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='test_id',
            new_name='quiz_id',
        ),
    ]
