# Generated by Django 4.0.4 on 2022-11-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0076_assessment_collection_quiz_quiz_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
    ]
