# Generated by Django 4.0.4 on 2022-11-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0077_assessment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
