# Generated by Django 4.0.4 on 2022-11-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0078_collection_collection_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='collection_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='collection_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
