# Generated by Django 4.0.4 on 2022-11-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieszkolni_app', '0079_quiz_collection_id_quiz_collection_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.CharField(max_length=200),
        ),
    ]
