from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.home, name="home"),
    path('vocabulary.html', views.vocabulary, name="vocabulary"),
    path('sentences.html', views.sentences, name="sentences"),
    path('view_answer.html', views.view_answer, name="view_answer"),
    path('congratulations.html', views.congratulations, name="congratulations"),
    path('options.html', views.options, name="options"),
    path('login_user.html', views.login_user, name="login_user"),
    path('logout_user.html', views.logout_user, name="logout_user"),
    path('staff.html', views.staff, name="staff"),
    path('profile.html', views.profile, name="profile"),
    path('staff_menu.html', views.staff_menu, name="staff_menu"),
    path('profile_menu.html', views.profile_menu, name="profile_menu"),
    path('register_user.html', views.register_user, name="register_user"),
    path('register_client.html', views.register_client, name="register_client"),
    path('submit_assignment.html', views.submit_assignment, name="submit_assignment"),
    path('upload_curriculum.html', views.upload_curriculum, name="upload_curriculum"),
    path('add_curriculum.html', views.add_curriculum, name="add_curriculum"),
    path('assignments.html', views.assignments, name="assignments"),
    path('assignment.html', views.assignment, name="assignment"),
    path('submit_assignment_automatically.html.html', views.submit_assignment, name="submit_assignment_automatically"),
    path('list_of_submissions.html', views.list_of_submissions, name="list_of_submissions"),
    path('list_of_assignments_to_grade.html', views.list_of_assignments_to_grade, name="list_of_assignments_to_grade"),
    path('footer.html.html', views.footer, name="footer"),
    path('display_curricula.html', views.display_curricula, name="display_curricula"),
    path('coach.html', views.coach, name="coach"),
    path('coach_menu.html', views.coach_menu, name="coach_menu"),
    path('session_mode.html', views.session_mode, name="session_mode"),
    path('agenda.html', views.agenda, name="agenda"),
    path('check_homework.html', views.check_homework, name="check_homework"),
    path('switch_clients.html', views.switch_clients, name="switch_clients"),
    path('my_pronunciation.html', views.my_pronunciation, name="my_pronunciation"),
    path('upload_dictionary.html', views.upload_dictionary, name="upload_dictionary"),
    path('upload_catalogues.html', views.upload_catalogues, name="upload_catalogues"),
    path('upload_sentence_stock.html', views.upload_sentence_stock, name="upload_sentence_stock"),
    path('upload_sets.html', views.upload_sets, name="upload_sets"),
    path('sentence_stock.html', views.sentence_stock, name="sentence_stock"),
    path('composer.html', views.composer, name="composer"),
    path('composed_sentences.html', views.composed_sentences, name="composed_sentences"),
    path('grade_sentences.html', views.grade_sentences, name="grade_sentences"),
    path('dictionary.html', views.dictionary, name="dictionary"),
    path('translate_wordbook.html', views.translate_wordbook, name="translate_wordbook"),
    path('approve_wordbook.html', views.approve_wordbook, name="approve_wordbook"),
    path('translate_sentencebook.html', views.translate_sentencebook, name="translate_sentencebook"),
    path('approve_sentencebook.html', views.approve_sentencebook, name="approve_sentencebook"),
    path('edit_card.html', views.edit_card, name="edit_card"),
    path('catalogues.html', views.catalogues, name="catalogues"),
    path('catalogues_list_of_phrases.html', views.catalogues_list_of_phrases, name="catalogues_list_of_phrases"),
    path('prompts.html', views.prompts, name="prompts"),
    path('memories.html', views.memories, name="memories"),
    path('stream.html', views.stream, name="stream"),
    path('library.html', views.library, name="library"),
    path('library_line.html', views.library_line, name="library_line"),
    path('report_reading.html', views.report_reading, name="report_reading"),
    path('repertoire.html', views.repertoire, name="repertoire"),
    path('repertoire_line.html', views.repertoire_line, name="repertoire_line"),
    path('report_listening.html', views.report_listening, name="report_listening"),
    path('download_assignments.html', views.download_assignments, name="download_assignments"),
       ]
